# Generated by Django 4.1.7 on 2024-02-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("weight", models.IntegerField(default=0)),
                ("height", models.IntegerField(default=0)),
                ("gender", models.CharField(default="unknown", max_length=100)),
                ("age", models.IntegerField(default=0)),
                (
                    "pal",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("1.2", "1.2"),
                            ("1.3", "1.3"),
                            ("1.4", "1.4"),
                            ("1.5", "1.5"),
                            ("1.6", "1.6"),
                            ("1.7", "1.7"),
                            ("1.8", "1.8"),
                            ("1.9", "1.9"),
                            ("2.0", "2.0"),
                            ("2.2", "2.2"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CalculatedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi", models.FloatField(default=0)),
                ("bmi_category", models.CharField(default="unknown", max_length=100)),
                ("bmr", models.FloatField(default=0)),
                (
                    "pal",
                    models.CharField(
                        choices=[
                            ("unknown", "unknown"),
                            ("1.2", "1.2"),
                            ("1.3", "1.3"),
                            ("1.4", "1.4"),
                            ("1.5", "1.5"),
                            ("1.6", "1.6"),
                            ("1.7", "1.7"),
                            ("1.8", "1.8"),
                            ("1.9", "1.9"),
                            ("2.0", "2.0"),
                            ("2.2", "2.2"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                ("tmr", models.FloatField(default=0)),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calculator.person",
                    ),
                ),
            ],
        ),
    ]
