# Generated by Django 4.1.7 on 2024-02-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculateddata",
            name="bmr",
            field=models.FloatField(default=0),
        ),
    ]
