# Generated by Django 4.1.7 on 2024-02-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculateddata",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculated_data",
                to="calculator.person",
            ),
        ),
    ]
