# Generated by Django 4.1.7 on 2024-02-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_calculateddata_bmr"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="pal",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("1.2", "1.2"),
                    ("1.3", "1.3"),
                    ("1.4", "1.4"),
                    ("1.5", "1.5"),
                    ("1.6", "1.6"),
                    ("1.7", "1.7"),
                    ("1.8", "1.8"),
                    ("1.9", "1.9"),
                    ("2.0", "2.0"),
                    ("2.2", "2.2"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="calculateddata",
            name="pal",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("1.2", "1.2"),
                    ("1.3", "1.3"),
                    ("1.4", "1.4"),
                    ("1.5", "1.5"),
                    ("1.6", "1.6"),
                    ("1.7", "1.7"),
                    ("1.8", "1.8"),
                    ("1.9", "1.9"),
                    ("2.0", "2.0"),
                    ("2.2", "2.2"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
    ]
