# Generated by Django 4.1.7 on 2024-02-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_alter_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("other", "other"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=8,
            ),
        ),
    ]
