# Generated by Django 4.1.7 on 2024-02-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0004_alter_person_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
