# Generated by Django 4.1.7 on 2024-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0005_alter_person_age_alter_person_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "male"), ("female", "female")],
                max_length=8,
                null=True,
            ),
        ),
    ]
