# Generated by Django 4.1.7 on 2024-02-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0007_alter_calculateddata_pal_alter_person_pal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculateddata",
            name="bmi",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="calculateddata",
            name="bmi_category",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="calculateddata",
            name="bmr",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="calculateddata",
            name="tmr",
            field=models.FloatField(null=True),
        ),
    ]
